# basic options
title: JI LAB
author: Ni Ji
email: niji@cibr.ac.cn
description: Computational Neuroscience, Navigation Behavior & Decision-Making
# github username: zhou-neurolab



# Build settings
markdown: kramdown
theme: minima

font-awesome:
  assets: true
  
asciidoctor:
  attributes:
    idprefix: _
    icons: font
    source-highlighter: coderay
    coderay-css: style

#    coderay-stylesheet: /css/coderay-asciidoctor.css
plugins:
  - jekyll-feed  
  

header_pages:
  - People.md
  - Research.md
  - Publications.md
  - News.md
  - Resources.md
  - Fun.md
  - Join.md

url: "https://jilab-cibr.github.io/"  # <-- 换成您自己的域名
baseurl: ""   