# basic options
title: Zhou Lab
author: Jingfeng Zhou
email: zhou.neurolab@gmail.com
description: Laboratory of Behavioral and Systems Neuroscience at the Chinese Institute on Brain Research, Beijing
# github username: zhou-neurolab

# Build settings
markdown: kramdown
theme: minima

header_pages:
  - Research.md
  - Publications.md
  - People.md
  - News.md
  - Outreach.md
  - Join.md
