# basic options
title: Zhou Lab
author: Jingfeng Zhou
email: jingfeng.zhou@cibr.ac.cn
description: Laboratory of Behavioral and Systems Neuroscience
# github username: zhou-neurolab



# Build settings
markdown: kramdown
theme: minima

header_pages:
  - People.md
  - Research.md
  - Publications.md
  - News.md
  - Resources.md
  - Fun.md
  - Join.md
