# basic options
title: Zhou Lab
author: Jingfeng Zhou
email: zhou.neurolab@gmail.com
description: Laboratory of Behavioral and Systems Neuroscience at the Chinese Institute for Brain Research, Beijing
# github username: zhou-neurolab

# Build settings
markdown: kramdown
theme: minima
# permalink: /:categories/: title/

header_pages:
  - People.md
  - Research.md
  - Publications.md
  - News.md
  - Links.md
  - Join.md
