# basic options
title: Zhou Lab
author: Jingfeng Zhou
email: zhou.neurolab@gmail.com
description: Behavioral and Systems Neuroscience
# github username: zhou-neurolab

# Build settings
markdown: kramdown
theme: minima

header_pages:
  - Research.md
  - Publications.md
  - People.md
  - News.md
  - Outreach.md
  - Join.md
