# basic options
title: ZHOU LAB
author: Jingfeng Zhou
email: jingfeng.zhou@cibr.ac.cn
description: Behavioral & Systems Neuroscience Laboratory
# github username: zhou-neurolab



# Build settings
markdown: kramdown
theme: minima

font-awesome:
  assets: true
  
asciidoctor:
  attributes:
    idprefix: _
    icons: font
    source-highlighter: coderay
    coderay-css: style

#    coderay-stylesheet: /css/coderay-asciidoctor.css
plugins:
  - jekyll-feed  
  

header_pages:
  - People.md
  - Research.md
  - Publications.md
  - News.md
  - Resources.md
  - Fun.md
  - Join.md
