# basic options
title: Zhou Lab
author: Jingfeng Zhou
email: <a href="https://zhoulab.cibr.ac.cn">ICP备案号：京ICP备18029179号</a>
description: Laboratory of Behavioral and Systems Neuroscience at the Chinese Institute for Brain Research, Beijing
# github username: zhou-neurolab



# Build settings
markdown: kramdown
theme: minima

header_pages:
  - People.md
  - Research.md
  - Publications.md
  - News.md
  - Resources.md
  - Fun.md
  - Join.md
